// lib/screens/team/team_management_screen.dart

import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:findus_app/constants/app_colors.dart';
import 'package:findus_app/models/team_member.dart';
import 'package:findus_app/screens/team/team_member_dashboard_screen.dart';

class TeamManagementScreen extends StatefulWidget {
  final String userId; // Business Owner's UID

  const TeamManagementScreen({
    super.key,
    required this.userId,
  });

  @override
  State<TeamManagementScreen> createState() => _TeamManagementScreenState();
}

class _TeamManagementScreenState extends State<TeamManagementScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _phoneController = TextEditingController();

  String _selectedRole = "staff";
  bool _isInviting = false;

  // Firestore reference helper
  CollectionReference get _teamCollection => FirebaseFirestore.instance
      .collection('users')
      .doc(widget.userId)
      .collection('team_members');

  @override
  void dispose() {
    _phoneController.dispose();
    super.dispose();
  }

  // --- Actions ---

  Future<void> _inviteMember() async {
    if (!_formKey.currentState!.validate()) return;

    // Hide keyboard
    FocusScope.of(context).unfocus();

    setState(() => _isInviting = true);

    final phone = _phoneController.text.trim();

    try {
      // 1. Check if user already exists in team
      final existingCheck = await _teamCollection
          .where('phone', isEqualTo: phone)
          .get();

      if (existingCheck.docs.isNotEmpty) {
        throw "This member is already in your team.";
      }

      // 2. Add to Firestore (Optimistic Update approach is safer handled by Stream)
      final newMember = TeamMember(
        id: '', // ID will be generated by Firestore
        name: "Invited User", // In real app, fetch name from 'users' collection if exists
        phone: phone,
        role: _selectedRole,
        isPending: true,
        joinedAt: DateTime.now(),
      );

      await _teamCollection.add(newMember.toMap());

      if (mounted) {
        _phoneController.clear();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Invitation sent successfully!"),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text("Error: ${e.toString()}"),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isInviting = false);
    }
  }

  Future<void> _confirmRemoveMember(TeamMember member) async {
    final bool? confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text("Remove Member?"),
        content: Text("Are you sure you want to remove ${member.name} from the team?"),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text("Cancel"),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text("Remove"),
          ),
        ],
      ),
    );

    if (confirm == true) {
      await _removeMember(member.id);
    }
  }

  Future<void> _removeMember(String docId) async {
    try {
      await _teamCollection.doc(docId).delete();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Member removed.")),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Failed to remove member.")),
        );
      }
    }
  }

  // --- Calculations ---

  Map<String, dynamic> _calculateStats(List<TeamMember> members) {
    int totalCompleted = 0;
    int totalInProgress = 0;

    double totalEarnings = 0.0;
    double totalRating = 0.0;

    int ratedMembers = 0;
    int pendingCount = 0;

    for (var m in members) {
      if (m.isPending) {
        pendingCount++;
      } else {
        totalCompleted += m.jobsCompleted;
        totalInProgress += m.jobsInProgress;
        totalEarnings += m.totalEarnings; // এখন double এর সাথে double যোগ হবে (ঠিক আছে)
        if (m.rating > 0) {
          totalRating += m.rating;
          ratedMembers++;
        }
      }
    }

    double avgRating = ratedMembers > 0 ? totalRating / ratedMembers : 0.0;

    return {
      'completed': totalCompleted,
      'inProgress': totalInProgress,
      'earnings': totalEarnings.toStringAsFixed(2), // 2 ঘর পর্যন্ত দশমিক দেখাবে
      'avgRating': avgRating,
      'pending': pendingCount,
      'size': members.length,
    };
  }

  // --- UI Builders ---

  void _showTeamDashboard(List<TeamMember> members) {
    final stats = _calculateStats(members);

    showModalBottomSheet(
      context: context,
      backgroundColor: AppColors.bgBlue,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(18)),
      ),
      builder: (ctx) => _DashboardBottomSheet(stats: stats),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgBlue,
      appBar: AppBar(
        title: const Text(
          "Team Management",
          style: TextStyle(color: AppColors.brandDark, fontWeight: FontWeight.bold),
        ),
        backgroundColor: AppColors.brandLight,
        iconTheme: const IconThemeData(color: AppColors.brandDark),
        elevation: 0,
      ),
      body: Column(
        children: [
          _buildInviteSection(),
          const Divider(height: 1, thickness: 1),
          Expanded(child: _buildTeamList()),
        ],
      ),
      // Only show FAB if we have data (Handled inside logic or passed safe list)
      // Here we rely on the StreamBuilder to provide data, so we can wrap FAB logic or
      // better yet, just query the cache or use a provider. For simplicity, we
      // will pass the current stream data if possible, but FAB is outside stream.
      // So we will modify the design: Put the stats button inside the list header
      // OR fetch data again (not ideal).
      // Best Approach: Wrap Body in StreamBuilder.
    );
  }

  Widget _buildInviteSection() {
    return Container(
      padding: const EdgeInsets.all(16),
      color: Colors.white,
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "Invite a team member",
              style: TextStyle(fontWeight: FontWeight.bold, color: AppColors.brandDark),
            ),
            const SizedBox(height: 12),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  flex: 2,
                  child: TextFormField(
                    controller: _phoneController,
                    keyboardType: TextInputType.phone,
                    validator: (val) {
                      if (val == null || val.isEmpty) return 'Required';
                      if (val.length < 11) return 'Invalid phone';
                      return null;
                    },
                    decoration: InputDecoration(
                      labelText: "Phone number",
                      hintText: "017XXXXXXXX",
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
                      isDense: true,
                    ),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  flex: 1,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: DropdownButtonHideUnderline(
                      child: DropdownButton<String>(
                        value: _selectedRole,
                        isExpanded: true,
                        items: const [
                          DropdownMenuItem(value: "manager", child: Text("Manager")),
                          DropdownMenuItem(value: "staff", child: Text("Staff")),
                        ],
                        onChanged: (v) {
                          if (v != null) setState(() => _selectedRole = v);
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              height: 45,
              child: ElevatedButton(
                onPressed: _isInviting ? null : _inviteMember,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.brandMain,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  elevation: 0,
                ),
                child: _isInviting
                    ? const SizedBox(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                )
                    : const Text(
                  "SEND INVITE",
                  style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTeamList() {
    return StreamBuilder<QuerySnapshot>(
      stream: _teamCollection.snapshots(),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Center(child: Text("Error: ${snapshot.error}"));
        }
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }

        final data = snapshot.data?.docs ?? [];

        // Convert Firestore docs to Models
        final List<TeamMember> members = data
            .map((doc) => TeamMember.fromMap(doc.id, doc.data() as Map<String, dynamic>))
            .toList();

        if (members.isEmpty) {
          return const Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.groups_outlined, size: 60, color: Colors.grey),
                SizedBox(height: 10),
                Text("No team members yet.", style: TextStyle(color: Colors.grey)),
              ],
            ),
          );
        }

        return Stack(
          children: [
            ListView.separated(
              padding: const EdgeInsets.only(bottom: 80, top: 10), // Space for FAB
              itemCount: members.length,
              separatorBuilder: (ctx, i) => const Divider(height: 1),
              itemBuilder: (ctx, i) {
                return _TeamMemberTile(
                  member: members[i],
                  onTapDashboard: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => TeamMemberDashboardScreen(member: members[i]),
                    ),
                  ),
                  onTapRemove: () => _confirmRemoveMember(members[i]),
                );
              },
            ),

            // FAB Positioned manually or using scaffold property with Stream data passed
            Positioned(
              right: 16,
              bottom: 16,
              child: FloatingActionButton.extended(
                onPressed: () => _showTeamDashboard(members),
                backgroundColor: AppColors.brandMain,
                icon: const Icon(Icons.dashboard_customize),
                label: const Text("Stats", style: TextStyle(fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        );
      },
    );
  }
}

// --- Extracted Widgets for Cleaner Code ---

class _TeamMemberTile extends StatelessWidget {
  final TeamMember member;
  final VoidCallback onTapDashboard;
  final VoidCallback onTapRemove;

  const _TeamMemberTile({
    required this.member,
    required this.onTapDashboard,
    required this.onTapRemove,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: ListTile(
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        leading: CircleAvatar(
          backgroundColor: member.role == "manager" ? Colors.orange.shade100 : Colors.blue.shade100,
          foregroundColor: member.role == "manager" ? Colors.orange.shade800 : Colors.blue.shade800,
          child: Text(
            member.name.isNotEmpty ? member.name[0].toUpperCase() : "?",
            style: const TextStyle(fontWeight: FontWeight.bold),
          ),
        ),
        title: Text(
          member.name,
          style: const TextStyle(fontWeight: FontWeight.w600),
        ),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 4),
            Text(member.phone, style: TextStyle(color: Colors.grey[600], fontSize: 13)),
            const SizedBox(height: 4),
            Row(
              children: [
                _StatusBadge(text: member.role.toUpperCase(), color: Colors.blueGrey),
                const SizedBox(width: 6),
                if (member.isPending)
                  const _StatusBadge(text: "PENDING", color: Colors.amber),
              ],
            ),
          ],
        ),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            IconButton(
              icon: const Icon(Icons.dashboard_outlined, color: AppColors.brandMain),
              onPressed: onTapDashboard,
              tooltip: "View Dashboard",
            ),
            IconButton(
              icon: const Icon(Icons.delete_outline, color: Colors.redAccent),
              onPressed: onTapRemove,
              tooltip: "Remove Member",
            ),
          ],
        ),
      ),
    );
  }
}

class _StatusBadge extends StatelessWidget {
  final String text;
  final Color color;

  const _StatusBadge({required this.text, required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(4),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Text(
        text,
        style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: color),
      ),
    );
  }
}

class _DashboardBottomSheet extends StatelessWidget {
  final Map<String, dynamic> stats;

  const _DashboardBottomSheet({required this.stats});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 30),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: Colors.grey[300],
              borderRadius: BorderRadius.circular(10),
            ),
          ),
          const SizedBox(height: 16),
          const Text(
            "Team Overview",
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.brandDark),
          ),
          const SizedBox(height: 20),
          Row(
            children: [
              _StatChip(
                label: "Completed",
                value: stats['completed'].toString(),
                icon: Icons.check_circle_outline,
                color: Colors.green,
              ),
              const SizedBox(width: 12),
              _StatChip(
                label: "Running",
                value: stats['inProgress'].toString(),
                icon: Icons.access_time,
                color: Colors.orange,
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              _StatChip(
                label: "Earnings",
                value: "৳${stats['earnings']}",
                icon: Icons.currency_exchange,
                color: AppColors.brandMain,
              ),
              const SizedBox(width: 12),
              _StatChip(
                label: "Avg Rating",
                value: stats['avgRating'].toStringAsFixed(1),
                icon: Icons.star_rounded,
                color: Colors.amber,
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              _StatChip(
                label: "Pending",
                value: stats['pending'].toString(),
                icon: Icons.pending_outlined,
                color: Colors.redAccent,
              ),
              const SizedBox(width: 12),
              _StatChip(
                label: "Total Members",
                value: stats['size'].toString(),
                icon: Icons.group_outlined,
                color: AppColors.brandDark,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _StatChip extends StatelessWidget {
  final String label;
  final String value;
  final IconData icon;
  final Color color;

  const _StatChip({
    required this.label,
    required this.value,
    required this.icon,
    required this.color,
  });

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.05),
              blurRadius: 10,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: color.withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, size: 20, color: color),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    value,
                    style: const TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                      color: AppColors.brandDark,
                    ),
                  ),
                  Text(
                    label,
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey[600],
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}