// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcb24nf_2Hzr7Drb-u3gDFCvaZytNcrY',
    appId: '1:22176787238:web:181d87a60430f8b2dbefe7',
    messagingSenderId: '22176787238',
    projectId: 'findus-prod',
    authDomain: 'findus-prod.firebaseapp.com',
    storageBucket: 'findus-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqgYsosm4VkE026x0v_BhELoZVKR3U4oU',
    appId: '1:22176787238:android:541f4a58f60695bddbefe7',
    messagingSenderId: '22176787238',
    projectId: 'findus-prod',
    storageBucket: 'findus-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYgx-9l9BYf2EG5UhqjMmuZnrBXlck8s',
    appId: '1:22176787238:ios:426d1608dd13e4dbdbefe7',
    messagingSenderId: '22176787238',
    projectId: 'findus-prod',
    storageBucket: 'findus-prod.firebasestorage.app',
    iosBundleId: 'com.example.findusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYgx-9l9BYf2EG5UhqjMmuZnrBXlck8s',
    appId: '1:22176787238:ios:426d1608dd13e4dbdbefe7',
    messagingSenderId: '22176787238',
    projectId: 'findus-prod',
    storageBucket: 'findus-prod.firebasestorage.app',
    iosBundleId: 'com.example.findusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCcb24nf_2Hzr7Drb-u3gDFCvaZytNcrY',
    appId: '1:22176787238:web:d8cd553e690a4aacdbefe7',
    messagingSenderId: '22176787238',
    projectId: 'findus-prod',
    authDomain: 'findus-prod.firebaseapp.com',
    storageBucket: 'findus-prod.firebasestorage.app',
  );
}
